CREATE TABLE MEMBERS(
MNO NUMBER,
MID VARCHAR2(60) NOT NULL,
MNAME VARCHAR2(50) NOT NULL,
EMAIL VARCHAR2(40) NOT NULL,
PWD VARCHAR2(100) NOT NULL,
CRE_DATE DATE NOT NULL,
MOD_DATE DATE NOT NULL,
PHONENO NUMBER NOT NULL,
SELECT1 VARCHAR2(10) NOT NULL,
SELECT2 VARCHAR2(10) NOT NULL,
SELECT3 VARCHAR2(10) NOT NULL,
SELECT4 VARCHAR2(10) NOT NULL
);

 COMMENT ON TABLE MEMBERS IS '회원기본정보';
 
 COMMENT ON COLUMN MEMBERS.MNO IS '회원정보';
  COMMENT ON COLUMN MEMBERS.MID IS '회원아이디';
 COMMENT ON COLUMN MEMBERS.EMAIL IS '이메일';
 COMMENT ON COLUMN MEMBERS.PWD IS '암호';
 COMMENT ON COLUMN MEMBERS.MNAME IS '이름';
 COMMENT ON COLUMN MEMBERS.CRE_DATE IS '가입일';
 COMMENT ON COLUMN MEMBERS.MOD_DATE IS '마지막암호변경일';
 COMMENT ON COLUMN MEMBERS.PHONENO IS '휴대폰번호';
 COMMENT ON COLUMN MEMBERS.SELECT1 IS '개인정보제3자제공(선택약관1)';
 COMMENT ON COLUMN MEMBERS.SELECT2 IS '개인정보수집및이용(선택약관2)';
 COMMENT ON COLUMN MEMBERS.SELECT3 IS '위치정보이용약관(선택약관3)';
 COMMENT ON COLUMN MEMBERS.SELECT4 IS '혜택알림수신(선택약관4)';

 ALTER TABLE MEMBERS
 ADD CONSTRAINT MEMBERS_MNO_PK PRIMARY KEY(MNO);

 CREATE SEQUENCE MEMBERS_MNO_SEQ
 INCREMENT BY 1
 START WITH 1;
 
 
 DESC MEMBERS;
 
SELECT *
FROM user_constraints
WHERE TABLE_NAME = 'MEMBERS';
 
CREATE TABLE SAMPLEBOARD(
BNO NUMBER NOT NULL,
MNO NUMBER NOT NULL,
WMID VARCHAR2(50) NOT NULL,
CTITLE VARCHAR2(100) NOT NULL,
BCONTENTS VARCHAR2(4000) NOT NULL,
BCRE_DATE DATE NOT NULL,
BMOD_DATE DATE NOT NULL,
BVIEWS NUMBER NOT NULL,
BREPLY NUMBER NOT NULL
);


 COMMENT ON TABLE SAMPLEBOARD IS '샘플 게시판';
 
 COMMENT ON COLUMN SAMPLEBOARD.BNO IS '게시판번호';
 COMMENT ON COLUMN SAMPLEBOARD.MNO IS '회원번호';
 COMMENT ON COLUMN SAMPLEBOARD.WMID IS '작성자ID';
 COMMENT ON COLUMN SAMPLEBOARD.CTITLE IS '제목';
 COMMENT ON COLUMN SAMPLEBOARD.BCONTENTS IS '내용';
 COMMENT ON COLUMN SAMPLEBOARD.BCRE_DATE IS '작성일';
 COMMENT ON COLUMN SAMPLEBOARD.BMOD_DATE IS '마지막수정일';
 COMMENT ON COLUMN SAMPLEBOARD.BVIEWS IS '조회수';
 COMMENT ON COLUMN SAMPLEBOARD.BREPLY IS '댓글수';


 ALTER TABLE SAMPLEBOARD
 ADD CONSTRAINT SAMPLEBOARD_BNO_PK PRIMARY KEY(BNO);

 ALTER TABLE SAMPLEBOARD
 ADD CONSTRAINT SAMPLEBOARD_MNO_FK FOREIGN KEY(MNO) REFERENCES MEMBERS(MNO);

 
 CREATE SEQUENCE SAMPLEBOARD_BNO_SEQ
 INCREMENT BY 1
 START WITH 1;
 
 DESC SAMPLEBOARD;
 
 SELECT *
FROM user_constraints
WHERE TABLE_NAME = 'SAMPLEBOARD';

DESC MEMBERS;

 INSERT INTO MEMBERS
 VALUE(MNO, MID, MNAME, EMAIL, PWD, CRE_DATE, MOD_DATE, PHONENO, SELECT1, SELECT2, SELECT3, SELECT4)
 VALUES(MEMBERS_MNO_SEQ.NEXTVAL, 'admin1', '홍길동','ADMIN1@test.com', 'ADMIN12', SYSDATE, SYSDATE,01012341234,'TRUE','TRUE','FALSE','FALSE');
 
 INSERT INTO MEMBERS
 VALUE(MNO, MID, MNAME, EMAIL, PWD, CRE_DATE, MOD_DATE, PHONENO, SELECT1, SELECT2, SELECT3, SELECT4)
 VALUES(MEMBERS_MNO_SEQ.NEXTVAL, 'admin2', '손진원','ADMIN2@test.com', 'ADMIN12', SYSDATE, SYSDATE,01013241234,'TRUE','TRUE','FALSE','FALSE');
 
  INSERT INTO MEMBERS
 VALUE(MNO, MID, MNAME, EMAIL, PWD, CRE_DATE, MOD_DATE, PHONENO, SELECT1, SELECT2, SELECT3, SELECT4)
 VALUES(MEMBERS_MNO_SEQ.NEXTVAL, 'admin3', '이경준','ADMIN3@test.com', 'ADMIN12', SYSDATE, SYSDATE,01014441234,'FALSE','TRUE','FALSE','TRUE');
 
  INSERT INTO MEMBERS
 VALUE(MNO, MID, MNAME, EMAIL, PWD, CRE_DATE, MOD_DATE, PHONENO, SELECT1, SELECT2, SELECT3, SELECT4)
 VALUES(MEMBERS_MNO_SEQ.NEXTVAL, 'admin4', '이승환','ADMIN4@test.com', 'ADMIN12', SYSDATE, SYSDATE,01012341384,'TRUE','FALSE','TRUE','FALSE');
 
  INSERT INTO MEMBERS
 VALUE(MNO, MID, MNAME, EMAIL, PWD, CRE_DATE, MOD_DATE, PHONENO, SELECT1, SELECT2, SELECT3, SELECT4)
 VALUES(MEMBERS_MNO_SEQ.NEXTVAL, 'admin5', '이몽룡','ADMIN5@test.com', 'ADMIN12', SYSDATE, SYSDATE,01034341111,'TRUE','FALSE','FALSE','TRUE');
 
  INSERT INTO MEMBERS
 VALUE(MNO, MID, MNAME, EMAIL, PWD, CRE_DATE, MOD_DATE, PHONENO, SELECT1, SELECT2, SELECT3, SELECT4)
 VALUES(MEMBERS_MNO_SEQ.NEXTVAL, 'admin6', 'admin','ADMIN6@test.com', 'ADMIN12', SYSDATE, SYSDATE,01011111111,'TRUE','FALSE','FALSE','TRUE');
 
   INSERT INTO MEMBERS
 VALUE(MNO, MID, MNAME, EMAIL, PWD, CRE_DATE, MOD_DATE, PHONENO, SELECT1, SELECT2, SELECT3, SELECT4)
 VALUES(MEMBERS_MNO_SEQ.NEXTVAL, 'admin', 'TEST','ADMIN6@test.com', 'ADMIN12', SYSDATE, SYSDATE,01011111111,'TRUE','FALSE','FALSE','TRUE');
 
 SELECT *
 FROM MEMBERS;
 
 SELECT MNO 회원번호, MID 회원ID, MNAME 회원이름, EMAIL 이메일, PWD 비밀번호, CRE_DATE 생성날짜, MOD_DATE 수정날짜
    , PHONENO 폰번호, SELECT1 선택약관1, SELECT2 선택약관2,SELECT3 선택약관3,SELECT4 선택약관4
 FROM MEMBERS;
 
 DESC SAMPLEBOARD;
 SELECT *
 FROM SAMPLEBOARD;
 
 INSERT INTO SAMPLEBOARD
 VALUE(BNO, MNO, WMID, CTITLE, BCONTENTS, BCRE_DATE, BMOD_DATE, BVIEWS, BREPLY)
 VALUES(SAMPLEBOARD_BNO_SEQ.NEXTVAL, 6, 'admin', '새 스티커 상품이 출시되었네요~','제가정말사고싶은 뉴진스스티커인데 출시했데요',SYSDATE, SYSDATE,0,0);
 
  INSERT INTO SAMPLEBOARD
 VALUE(BNO, MNO, WMID, CTITLE, BCONTENTS, BCRE_DATE, BMOD_DATE, BVIEWS, BREPLY)
 VALUES(SAMPLEBOARD_BNO_SEQ.NEXTVAL, 6, 'admin', '입문자를 위한 안내','뉴진스팬클럽 버니즈~ 환영해욥',SYSDATE, SYSDATE,0,0);
 
  INSERT INTO SAMPLEBOARD
 VALUE(BNO, MNO, WMID, CTITLE, BCONTENTS, BCRE_DATE, BMOD_DATE, BVIEWS, BREPLY)
 VALUES(SAMPLEBOARD_BNO_SEQ.NEXTVAL, 6, 'admin', '웹사이트 만들 때 유용한 도구들','뭘까아아아아용?',SYSDATE, SYSDATE,0,0);
 
  INSERT INTO SAMPLEBOARD
 VALUE(BNO, MNO, WMID, CTITLE, BCONTENTS, BCRE_DATE, BMOD_DATE, BVIEWS, BREPLY)
 VALUES(SAMPLEBOARD_BNO_SEQ.NEXTVAL, 6, 'admin', '안녕하세요! 좋은 아침입니다','아니요하세요 안좋은아침인데요?',SYSDATE, SYSDATE,0,0);
 
INSERT INTO SAMPLEBOARD
VALUE(BNO, MNO, WMID, CTITLE, BCONTENTS, BCRE_DATE, BMOD_DATE, BVIEWS, BREPLY)
VALUES(SAMPLEBOARD_BNO_SEQ.NEXTVAL, 6, 'admin', '워드프레스 게시판 사용법1','이게 그렇게 돈이된다면서요?',SYSDATE, SYSDATE,0,0);
 
SELECT BNO 게시판번호, MNO 회원번호, WMID 작성자ID, CTITLE 글제목, BCONTENTS 글내용
    , BCRE_DATE 작성날짜, BMOD_DATE 수정날짜, BVIEWS 조회수, BREPLY 댓글수
FROM SAMPLEBOARD;
commit;
desc sampleboard;
SELECT BNO,WMID,CTITLE,BCONTENTS
FROM SAMPLEBOARD;
